
import { Inter } from 'next/font/google'
import './globals.scss'
import Navbar from '@/components/Navbar'
import LogContextProvider from '@/contexts/LogContextProvider'
import { NotesProvider } from '@/contexts/NoteContextProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Demo!!',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body  className={inter.className}>
<NotesProvider>
      <LogContextProvider>
      <Navbar/>
        {children}
      </LogContextProvider>
      </NotesProvider>

        </body>
    </html>
  )
}
